### ISSUE TITLE
Is this still needed?

### ISSUE THREAD

**Issue by einarpersson** [Opisek/obsidian-vim-langmap#2]
Hi!

Now that https://github.com/replit/codemirror-vim/pull/151 is merged, is this still needed or do you configure it with https://github.com/esm7/obsidian-vimrc-support for example?

If this is obsolete, perhaps add a friendly note to README

**Comment by Opisek** [comment]
Not yet obsolete! CodeMirror Vim was just released a new version with this feature a few days ago, so it might still take a few months until obsidian adopts it. I'll archive the repo once that happens.

The Vimrc plugin will also have to be adjusted to use that feature once it's in obsidian. I'll gladly make a PR once we're there and I hope for a quick merge from the maintainers.

**Comment by fluentnumbers** [comment]
> Not yet obsolete! CodeMirror Vim was just released a new version with this feature a few days ago, so it might still take a few months until obsidian adopts it. I'll archive the repo once that happens.
> 
> The Vimrc plugin will also have to be adjusted to use that feature once it's in obsidian. I'll gladly make a PR once we're there and I hope for a quick merge from the maintainers.

Did it happen yet? I am looking for a solution to the same problem and I am not sure which way to take - use this plugin or dig into how to do it in obsidian-vimrc?

**Comment by Opisek** [comment]
Still not in Obsidian.

**Comment by Opisek** [comment]
@fluentnumbers Still not in Obsidian.

You'll be able to tell when Obsidian updates the dependency by typing `:set langmap=""<Enter>`. It still outputs an error. Once it's ready, it will just close with no further information. At that point I can get a PR into vimrc going.

**Comment by Opisek** [comment]
@einarpersson @fluentnumbers Obsidian updated their dependencies. There seem to be some issues with the command `:set langmap=...`, but there should be another way to set the langmap using JavaScript. I'll try it later today and let you know.

**Comment by einarpersson** [comment]
Thanks, but I've migrated to Neovim (with obsidian.nvim and render-markdown.nvim) :)

**Comment by Opisek** [comment]
Sounds like a nice setup! I might try it myself someday.

For anyone else following this thread, it seems Obsidian has internally modified and *broken* the codemirror-vim code in the recent version, rendering the langmap feature non-functional: [Bug report](https://forum.obsidian.md/t/broken-vim-langmap/90262)

**Comment by Opisek** [comment]
Obsidian fixed their fork of codemirror-vim and langmaps work now. It seems that they work out of the box with [obsidian-vimrc-support](https://github.com/esm7/obsidian-vimrc-support).
